export type EaseFunction = (t: number) => number;

export type SpringParameters = {
  mass?: number;
  stiffness?: number;
  damping?: number;
  velocity?: number;
  duration?: number;
};

export type Ease = {
  /** Ease-in easing functions. */
  in: Ease_in_out_inOut;

  /** Ease-out easing functions. */
  out: Ease_in_out_inOut;

  /** Ease-in-out easing functions. */
  inOut: Ease_in_out_inOut;

  /** Default linear easing function. */
  linear: EaseFunction;

  /**
   * Defines a [cubic Bézier curve](https://developer.mozilla.org/en-US/docs/Glossary/Bezier_curve), similar to CSS's
   * **cubic-bezier** easing function.
   *
   * **CubicBezier** check out [animare docs](https://alabsi91.github.io/animare/api/plugins/ease/#cubicBezier) to learn more.
   *
   * @example
   *   ```js
   *   import animare from 'animare';
   *   import { ease } from 'animare/plugins';
   *
   *   animare.timeline([{ name: 'anim', to: 100, ease: ease.cubicBezier(0.25, 0.1, 0.25, 1) }], onUpdate);
   *   ```;
   */
  cubicBezier: (x1: number, y1: number, x2: number, y2: number) => EaseFunction;

  /**
   * Creates a custom easing function from an SVG path `d` attribute string.
   *
   * ⚠️ **Warning** ⚠️ Only accepts strings generated by the [Animare Ease
   * Visualizer](https://animare-ease-visualizer.netlify.app/) tool.
   *
   * @param pathString - The SVG path `d` attribute.
   */
  custom: (pathString: string) => EaseFunction;

  /**
   * Creates a custom easing function from an array of points.
   *
   * Use the [Animare Ease Visualizer](https://animare-ease-visualizer.netlify.app/) tool to create the easing function.
   *
   * **FromPoints** check out [animare docs](https://alabsi91.github.io/animare/api/plugins/ease/#frompoints) to learn more.
   *
   * @example
   *   ```js
   *   import animare from 'animare';
   *   import { ease } from 'animare/plugins';
   *   // Custom easing function generated by Animare Ease Visualizer tool
   *   import myEase from './myEase.js';
   *
   *   animare.timeline([{ name: 'anim', to: 100, ease: ease.fromPoints(myEase) }], onUpdate);
   *   ```;
   */
  fromPoints: (values: Float32List) => EaseFunction;

  /**
   * Creates a staircase easing function.
   *
   * **Steps** check out [animare docs](https://alabsi91.github.io/animare/api/plugins/ease/#steps) to learn more.
   *
   * @example
   *   ```js
   *   import animare from 'animare';
   *   import { ease } from 'animare/plugins';
   *
   *   animare.timeline([{ name: 'anim', to: 100, ease: ease.steps(5) }], onUpdate);
   *   ```;
   *
   * @param steps - The number of steps.
   * @param shouldStartAtIntervalBeginning - Whether to start at the beginning or at the end of each interval.
   */
  steps(steps?: number, shouldStartAtIntervalBeginning?: boolean): EaseFunction;
};

export type Ease_in_out_inOut = {
  /** **Back** check out [animare docs](https://alabsi91.github.io/animare/api/plugins/ease/#back) to learn more. */
  back: (c1?: number) => EaseFunction;

  /**
   * Creates a bouncing ball easing function.
   *
   * **Bounce** check out [animare docs](https://alabsi91.github.io/animare/api/plugins/ease/#bounce) to learn more.
   *
   * @param bounces - How many times the ball rebounds after the first drop. Defaults to `3`.
   * @param bounciness - How much speed the ball keeps on each rebound, from `0` (none) to `1` (all). Defaults to `0.5`.
   */
  bounce: (bounces?: number, bounciness?: number) => EaseFunction;

  /** **Cric** check out [animare docs](https://alabsi91.github.io/animare/api/plugins/ease/#cric) to learn more. */
  circ: EaseFunction;

  /** **Cubic** check out [animare docs](https://alabsi91.github.io/animare/api/plugins/ease/#cubic) to learn more. */
  cubic: EaseFunction;

  /**
   * Creates a spring-like easing function that overshoots the target and oscillates back.
   *
   * **Elastic** check out [animare docs](https://alabsi91.github.io/animare/api/plugins/ease/#elastic) to learn more.
   *
   * @param amplitude - How far it overshoots. Values below `1` are treated as `1`. Defaults to `1`.
   * @param period - How long one oscillation takes, as a fraction of the duration. Smaller means more wiggles. Defaults to `0.3`,
   *   or `0.45` for `inOut`.
   */
  elastic: (amplitude?: number, period?: number) => EaseFunction;

  /** **Expo** check out [animare docs](https://alabsi91.github.io/animare/api/plugins/ease/#expo) to learn more. */
  expo: EaseFunction;

  /** **Sine** check out [animare docs](https://alabsi91.github.io/animare/api/plugins/ease/#sine) to learn more. */
  sine: EaseFunction;

  /** **Quad** check out [animare docs](https://alabsi91.github.io/animare/api/plugins/ease/#quad) to learn more. */
  quad: EaseFunction;

  /** **Quart** check out [animare docs](https://alabsi91.github.io/animare/api/plugins/ease/#quart) to learn more. */
  quart: EaseFunction;

  /** **Quint** check out [animare docs](https://alabsi91.github.io/animare/api/plugins/ease/#quint) to learn more. */
  quint: EaseFunction;

  /** A power function. Position is equal to the Nth power of elapsed time. */
  poly: (n: number) => EaseFunction;

  /**
   * Creates a simple elastic interaction, similar to a spring oscillating back and forth.
   *
   * The default bounciness is `1`, which overshoots a little bit once. A bounciness of `0` doesn't overshoot at all, and a
   * bounciness of `N > 1` will overshoot about `N` times.
   *
   * **Wobble** check out [animare docs](https://alabsi91.github.io/animare/api/plugins/ease/#wobble) to learn more.
   */
  wobble: (bounciness?: number) => EaseFunction;

  /**
   * Creates a spring easing function.
   *
   * ⚠️ **Warning** ⚠️ The spring easing function will only look smooth at certain durations and with certain parameters.
   *
   * **Spring** check out [animare docs](https://alabsi91.github.io/animare/api/plugins/ease/#spring) to learn more.
   *
   * @example
   *   ```js
   *   import animare from 'animare';
   *   import { ease } from 'animare/plugins';
   *
   *   animare.timeline([
   *   {
   *     name: 'anim',
   *     to: 100,
   *     ease: ease.out.spring({ mass: 1, stiffness: 100, damping: 10, velocity: 0, duration: 1000 })
   *   }
   *   ], onUpdate);
   *   ```;
   */
  spring: (options?: SpringParameters) => EaseFunction;
};
