import cubicBezier from './cubicBezier.js';
import { customEase as custom } from './customEase.js';
import { fromPoints, linear, steps } from './ease.js';
import easeIn from './easeIn.js';
import easeInOut from './easeInOut.js';
import easeOut from './easeOut.js';

export const ease = {
  /** Ease-in functions. */
  in: easeIn,

  /** Ease-out functions. */
  out: easeOut,

  /** Ease-in-out functions. */
  inOut: easeInOut,

  /** Default linear easing function. */
  linear,

  /**
   * Defines a [cubic Bézier curve](https://developer.mozilla.org/en-US/docs/Glossary/Bezier_curve),
   * similar to CSS's **cubic-bezier** easing function.
   *
   * **Syntax:** `cubicBezier(X1: number, Y1: number, X2: number, Y2: number)`
   *
   * @example
   * ```js
   * import animare, { ease } from 'animare';
   *
   * animare([{ name: 'anim', to: 100, ease: ease.cubicBezier(0.25, 0.1, 0.25, 1) }], onUpdate);
   * ```
   */
  cubicBezier,

  /**
   * Creates a custom easing function from an SVG path `d` attribute string.
   *
   * ⚠️ **Warning** ⚠️ Only accepts strings generated by the [Animare Ease Visualizer](https://animare-ease-visualizer.netlify.app/) tool.
   *
   * @param pathString - The SVG path `d` attribute.
   * @param samples - The number of samples.
   */
  custom,

  /**
   * Creates a custom easing function from an array of points.
   *
   * Use the [Animare Ease Visualizer](https://animare-ease-visualizer.netlify.app/) tool to create the easing function.
   *
   * **Syntax:** `ease.fromPoints(values: Float32List)`
   *
   * @example
   * ```js
   * import animare, { ease } from 'animare';
   * // Custom easing function generated by Animare Ease Visualizer tool
   * import myEase from './myEase.js';
   *
   * animare([{ name: 'anim', to: 100, ease: ease.fromPoints(myEase) }], onUpdate);
   * ```
   */
  fromPoints,

  /**
   * Creates a staircase easing function.
   *
   * @param steps - The number of steps.
   * @param start - Whether to start at the beginning or at the end of each interval.
   *
   * @example
   * ```js
   * import animare, { ease } from 'animare';
   *
   * animare([{ name: 'anim', to: 100, ease: ease.steps(5) }], onUpdate);
   * ```
   */
  steps,
};
